import React from "react";
import {
  Link
} from 'react-router-dom';
import './policy.css'
import Header from '../../components/header'
import Footer from '../../components/footer'

export default class PrivacyPolicy extends React.Component {
  render() {
    const {
      privacyPolicy,
      loremIpsumDolorSi,
      oval,
      oval2,
      oval3,
      label1,
      faq,
      contact,
      privacyPolicy2,
      copyright2512021Al,
      fypsoundslogoProps,
      aboutProps,
      fypsoundslogo2Props,
    } = this.props;

    return (
      <div className="privacypolicy">
        <div className="container-center-horizontal">
          <div className="bar"></div>
        </div>
        <div className="container-center-horizontal">
          <h1 className="privacy-policy-C61RwL montserrat-bold-rose-pearl-24px">{privacyPolicy}</h1>
        </div>
        <div className="container-center-horizontal">
          <div className="policy-wrapper">
            <div className="policy-container">
                <h3>TERMS OF SERVICE FOR EMUQ TECH, INC. (“EMUQ”)</h3>
                <h3>FYP SOUNDS APP (www.fypsounds.com) A AUDIO DISTRIBUTION PLATFORM (THE “EMUQ WEBSITE/APPLICATION”).</h3>
                <h4>A AUDIO DISTRIBUTION PLATFORM (THE “EMUQ WEBSITE/APPLICATION”).</h4>
                 <div className="lorem-ipsum-dolor-si">
                <span>1. YOUR ACCEPTANCE</span><br/>
                BY USING OR VISITING ANY OF THE EMUQ WEBSITE/APPLICATION AND USING ANY OF ANY EMUQ APPLICATIONS, PRODUCTS, SOFTWARE, DATAX FEEDS, AND SERVICES PROVIDED TO YOU ON, FROM, OR THROUGH THE EMUQ WEBSITE/APPLICATION (COLLECTIVELY THE "SERVICE") YOU SIGNIFY YOUR AGREEMENT TO THESE TERMS AND CONDITIONS (THE "TERMS OF SERVICE"). IF YOU DO NOT AGREE TO ANY OF THESE TERMS, PLEASE DO NOT USE THE SERVICE.
                THIS SERVICE IS INTENDED TO FACILITATE THE DISTRIBUTION OF ARTISTS AND THEIR AUDIO CONTENT THROUGHOUT THE WORLD. BY USING THE SERVICE YOU AGREE THAT EMUQ MAY USE AND EXPLOIT YOUR CONTENT THROUGHOUT THE UNIVERSE, FEATURE YOU AND YOUR CONTENT ON THE EMUQ WEBSITE/APPLICATIONS, AND SUBMIT YOU AND YOUR CONTENT (AS HEREINAFTER DEFINED) TO STREAMING PLATFORM SERVICES & SOCIAL MEDIA. YOU AGREE THAT YOUR CONTENT, AND LINKS TO YOUR TIKTOK, FACEBOOK, INSTAGRAM, AND YOUR OTHER SOCIAL MEDIA PLATFORMS, MAY BE DISPLAYED ON THE EMUQ WEBSITE/APPLICATION AND CIRCULATED TO EXECUTIVES AND OTHER DECISION MAKERS AT MAJOR CORPORATIONS THROUGHOUT THE WORLD IN ORDER TO USE, EXPLOIT AND PROMOTE YOU AND YOUR CONTENT.
                ALTHOUGH WE MAY ATTEMPT TO NOTIFY YOU WHEN MAJOR CHANGES ARE MADE TO THESE TERMS OF SERVICE, YOU SHOULD PERIODICALLY REVIEW THE MOST UP-TO-DATE VERSION ON THE EMUQ WEBSITE/APPLICATION. EMUQ MAY, IN ITS SOLE DISCRETION, MODIFY OR REVISE THESE TERMS OF SERVICE AND POLICIES AT ANY TIME, AND YOU AGREE TO BE BOUND BY SUCH MODIFICATIONS OR REVISIONS. NOTHING IN THESE TERMS OF SERVICE SHALL BE DEEMED TO CONFER ANY THIRD-PARTY RIGHTS OR BENEFITS.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>2. SERVICE</span><br/>
                THESE TERMS OF SERVICE APPLY TO ALL USERS OF THE SERVICE, INCLUDING USERS WHO ARE ALSO CONTRIBUTORS OF CONTENT ON THE SERVICE. “CONTENT” INCLUDES THE TEXT, SOFTWARE, GRAPHICS, PHOTOS, SOUNDS, MUSIC, VIDEOS, AUDIOVISUAL COMBINATIONS, INTERACTIVE FEATURES AND OTHER MATERIALS YOU MAY VIEW ON, ACCESS THROUGH, OR CONTRIBUTE TO THE SERVICE. THE SERVICE INCLUDES ALL ASPECTS OF EMUQ, INCLUDING BUT NOT LIMITED TO ALL APPLICATIONS, PRODUCTS, SOFTWARE AND SERVICES OFFERED VIA THE EMUQ WEBSITE/APPLICATION OR ITS MOBILE APPLICATIONS AND OTHER APPLICATIONS.
                THE SERVICE MAY CONTAIN LINKS TO THIRD PARTY WEBSITES THAT ARE NOT OWNED OR CONTROLLED BY EMUQ. EMUQ HAS NO CONTROL OVER, AND ASSUMES NO RESPONSIBILITY FOR, THE CONTENT, PRIVACY POLICIES, OR PRACTICES OF ANY THIRD PARTY WEBSITES. IN ADDITION, EMUQ WILL NOT AND CANNOT CENSOR OR EDIT THE CONTENT OF ANY THIRD-PARTY SITE. BY USING THE SERVICE, YOU EXPRESSLY RELIEVE EMUQ FROM ANY AND ALL LIABILITY ARISING FROM YOUR USE OF ANY THIRD-PARTY WEBSITE. ACCORDINGLY, WE ENCOURAGE YOU TO BE AWARE WHEN YOU LEAVE THE SERVICE AND TO READ THE TERMS AND CONDITIONS AND PRIVACY POLICY OF EACH OTHER WEBSITE THAT YOU VISIT.
                SOME OF THE SERVICE IS SUPPORTED BY ADVERTISING REVENUE AND MAY DISPLAY ADVERTISEMENTS AND PROMOTIONS, AND YOU HEREBY AGREE THAT EMUQ MAY PLACE SUCH ADVERTISING AND PROMOTIONS ON THE SERVICE OR ON, ABOUT, OR IN CONJUNCTION WITH YOUR CONTENT. THE MANNER, MODE AND EXTENT OF SUCH ADVERTISING AND PROMOTIONS ARE SUBJECT TO CHANGE WITHOUT SPECIFIC NOTICE TO YOU.
                ALTHOUGH IT IS EMUQ'S INTENTION FOR THE SERVICE TO BE AVAILABLE AS MUCH AS POSSIBLE, THERE WILL BE OCCASIONS WHEN THE SERVICE MAY BE INTERRUPTED, INCLUDING, WITHOUT LIMITATION, FOR SCHEDULED MAINTENANCE OR UPGRADES, FOR EMERGENCY REPAIRS, OR DUE TO FAILURE OF TELECOMMUNICATIONS LINKS AND/OR EQUIPMENT. EMUQ WILL NOT BE LIABLE TO YOU FOR ANY MODIFICATION, SUSPENSION, OR DISCONTINUATION OF THE SERVICE OR LOSS OF ANY CONTENT.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>3. EMUQ ACCOUNTS</span><br/>
                IN ORDER TO ACCESS THE SERVICE BEYOND SIMPLY VIEWING, AND IN ORDER TO INTERACT OR POST ON THE SERVICE, YOU WILL HAVE TO CREATE A EMUQ ACCOUNT. YOU MAY NEVER USE ANOTHER'S ACCOUNT WITHOUT PERMISSION. WHEN CREATING YOUR ACCOUNT, YOU MUST PROVIDE ACCURATE AND COMPLETE INFORMATION. YOU ARE SOLELY RESPONSIBLE FOR THE ACTIVITY THAT OCCURS ON YOUR ACCOUNT, AND YOU MUST KEEP YOUR ACCOUNT PASSWORD SECURE. YOU MUST NOTIFY EMUQ IMMEDIATELY OF ANY BREACH OF SECURITY OR UNAUTHORIZED USE OF YOUR ACCOUNT.
                ALTHOUGH EMUQ WILL NOT BE LIABLE FOR YOUR LOSSES CAUSED BY ANY UNAUTHORIZED USE OF YOUR ACCOUNT, YOU MAY BE LIABLE FOR THE LOSSES OF EMUQ OR OTHERS DUE TO SUCH UNAUTHORIZED USE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>4. GENERAL USE OF THE SERVICE—PERMISSIONS AND RESTRICTIONS</span><br/>
                EMUQ HEREBY GRANTS YOU PERMISSION TO ACCESS AND USE THE SERVICE AS SET FORTH IN THESE TERMS OF SERVICE, PROVIDED THAT:
                YOU AGREE NOT TO DISTRIBUTE IN ANY MEDIUM ANY PART OF THE SERVICE OR THE CONTENT WITHOUT EMUQ'S PRIOR WRITTEN AUTHORIZATION, UNLESS EMUQ MAKES AVAILABLE THE MEANS FOR SUCH DISTRIBUTION THROUGH FUNCTIONALITY OFFERED BY THE SERVICE.
                YOU AGREE NOT TO ALTER OR MODIFY ANY PART OF THE SERVICE.
                YOU AGREE NOT TO ACCESS CONTENT THROUGH ANY TECHNOLOGY OR MEANS OTHER THAN THE PLAYBACK PAGES OF THE SERVICE ITSELF OR OTHER EXPLICITLY AUTHORIZED MEANS EMUQ MAY DESIGNATE.
                YOU AGREE NOT TO USE THE SERVICE FOR ANY OF THE FOLLOWING COMMERCIAL USES UNLESS YOU OBTAIN EMUQ'S PRIOR WRITTEN APPROVAL:
                THE SALE OF ACCESS TO THE SERVICE;
                THE SALE OF ADVERTISING, SPONSORSHIPS, OR PROMOTIONS PLACED ON OR WITHIN THE SERVICE OR CONTENT; OR
                THE SALE OF ADVERTISING, SPONSORSHIPS, OR PROMOTIONS ON ANY PAGE OF AN AD-ENABLED BLOG OR WEBSITE CONTAINING CONTENT DELIVERED VIA THE SERVICE.
                PROHIBITED COMMERCIAL USES DO NOT INCLUDE:
                UPLOADING ORIGINAL AUDIO, VIDEO, AUDIO/VIDEO OR TEXT CONTENT TO EMUQ TO PROMOTE YOURSELF OR YOUR ARTISTIC ENTERPRISE.
                IF YOU USE THE EMUQ APPLICATIONS, PRODUCTS, SOFTWARE, DATA FEEDS, AND SERVICES PROVIDED TO YOU, YOU AGREE THAT EMUQ MAY AUTOMATICALLY DOWNLOAD AND INSTALL UPDATES FROM TIME TO TIME. THESE UPDATES ARE DESIGNED TO IMPROVE, ENHANCE AND FURTHER DEVELOP THE APPLICATIONS, PRODUCTS, SOFTWARE, DATA FEEDS, AND SERVICES AND MAY TAKE THE FORM OF BUG FIXES, ENHANCED FUNCTIONS, NEW SOFTWARE MODULES AND COMPLETELY NEW VERSIONS. YOU AGREE TO RECEIVE SUCH UPDATES (AND PERMIT EMUQ TO DELIVER THESE TO YOU) AS PART OF YOUR USE OF THE APPLICATIONS, PRODUCTS, SOFTWARE, DATA FEEDS, AND SERVICES.
                YOU AGREE NOT TO USE OR LAUNCH ANY AUTOMATED SYSTEM, INCLUDING WITHOUT LIMITATION, "ROBOTS," "SPIDERS," OR "OFFLINE READERS," THAT ACCESSES THE SERVICE IN A MANNER THAT SENDS MORE REQUEST MESSAGES TO THE EMUQ SERVERS IN A GIVEN PERIOD OF TIME THAN A HUMAN CAN REASONABLY PRODUCE IN THE SAME PERIOD BY USING A CONVENTIONAL ON-LINE WEB BROWSER. NOTWITHSTANDING THE FOREGOING, EMUQ GRANTS THE OPERATORS OF PUBLIC SEARCH ENGINES PERMISSION TO USE SPIDERS TO COPY MATERIALS FROM THE SITE FOR THE SOLE PURPOSE OF AND SOLELY TO THE EXTENT NECESSARY FOR CREATING PUBLICLY AVAILABLE SEARCHABLE INDICES OF THE MATERIALS, BUT NOT CACHES OR ARCHIVES OF SUCH MATERIALS. EMUQ RESERVES THE RIGHT TO REVOKE THESE EXCEPTIONS EITHER GENERALLY OR IN SPECIFIC CASES. YOU AGREE NOT TO COLLECT OR HARVEST ANY PERSONALLY IDENTIFIABLE INFORMATION, INCLUDING ACCOUNT NAMES, FROM THE SERVICE, NOR TO USE THE COMMUNICATION SYSTEMS PROVIDED BY THE SERVICE (E.G., COMMENTS, EMAIL) FOR ANY COMMERCIAL SOLICITATION PURPOSES. YOU AGREE NOT TO SOLICIT, FOR COMMERCIAL PURPOSES, ANY USERS OF THE SERVICE WITH RESPECT TO THEIR CONTENT.
                IN YOUR USE OF THE SERVICE, YOU WILL COMPLY WITH ALL APPLICABLE LAWS.
                EMUQ RESERVES THE RIGHT TO DISCONTINUE ANY ASPECT OF THE SERVICE AT ANY TIME.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>5. YOUR USE OF CONTENT</span><br/>
                IN ADDITION TO THE GENERAL RESTRICTIONS ABOVE, THE FOLLOWING RESTRICTIONS AND CONDITIONS APPLY SPECIFICALLY TO YOUR USE OF CONTENT.
                THE CONTENT ON THE SERVICE, AND THE TRADEMARKS, SERVICE MARKS AND LOGOS ("MARKS") ON THE SERVICE, AND ALL OTHER INTELLECTUAL PROPERTY, ARE OWNED BY OR LICENSED TO EMUQ, SUBJECT TO COPYRIGHT AND OTHER INTELLECTUAL PROPERTY RIGHTS UNDER THE LAW.
                CONTENT IS PROVIDED TO YOU AS IS. YOU MAY ACCESS CONTENT FOR YOUR INFORMATION AND PERSONAL USE SOLELY AS INTENDED THROUGH THE PROVIDED FUNCTIONALITY OF THE SERVICE AND AS PERMITTED UNDER THESE TERMS OF SERVICE. YOU SHALL NOT DOWNLOAD ANY CONTENT UNLESS YOU SEE A “DOWNLOAD” OR SIMILAR LINK DISPLAYED BY EMUQ ON THE SERVICE FOR THAT CONTENT. YOU SHALL NOT COPY, REPRODUCE, DISTRIBUTE, TRANSMIT, BROADCAST, DISPLAY, SELL, LICENSE, OR OTHERWISE EXPLOIT ANY CONTENT FOR ANY OTHER PURPOSES WITHOUT THE PRIOR WRITTEN CONSENT OF EMUQ OR THE RESPECTIVE LICENSORS OF THE CONTENT. EMUQ AND ITS LICENSORS RESERVE ALL RIGHTS NOT EXPRESSLY GRANTED IN AND TO THE SERVICE AND THE CONTENT.
                YOU AGREE NOT TO CIRCUMVENT, DISABLE OR OTHERWISE INTERFERE WITH SECURITY-RELATED FEATURES OF THE SERVICE OR FEATURES THAT PREVENT OR RESTRICT USE OR COPYING OF ANY CONTENT OR ENFORCE LIMITATIONS ON USE OF THE SERVICE OR THE CONTENT THEREIN.
                YOU UNDERSTAND THAT WHEN USING THE SERVICE, YOU WILL BE EXPOSED TO CONTENT FROM A VARIETY OF SOURCES, AND THAT EMUQ IS NOT RESPONSIBLE FOR THE ACCURACY, USEFULNESS, SAFETY, OR INTELLECTUAL PROPERTY RIGHTS OF OR RELATING TO SUCH CONTENT. YOU FURTHER UNDERSTAND AND ACKNOWLEDGE THAT YOU MAY BE EXPOSED TO CONTENT THAT IS INACCURATE, OFFENSIVE, INDECENT, OR OBJECTIONABLE, AND YOU AGREE TO WAIVE, AND HEREBY DO WAIVE, ANY LEGAL OR EQUITABLE RIGHTS OR REMEDIES YOU HAVE OR MAY HAVE AGAINST EMUQ WITH RESPECT THERETO, AND, TO THE EXTENT PERMITTED BY APPLICABLE LAW, AGREE TO INDEMNIFY AND HOLD HARMLESS EMUQ, ITS OWNERS, OPERATORS, AFFILIATES, LICENSORS, AND LICENSEES TO THE FULLEST EXTENT ALLOWED BY LAW REGARDING ALL MATTERS RELATED TO YOUR USE OF THE SERVICE.
                 </div>
                <div className="lorem-ipsum-dolor-si">
                <span>6. YOUR CONTENT AND CONDUCT</span><br/>
                AS A EMUQ ACCOUNT HOLDER YOU MAY SUBMIT APPROPRIATE CONTENT TO THE SERVICE. YOU UNDERSTAND THAT EMUQ DOES NOT GUARANTEE ANY CONFIDENTIALITY WITH RESPECT TO ANY CONTENT YOU SUBMIT.
                YOU SHALL BE SOLELY RESPONSIBLE FOR YOUR OWN CONTENT AND THE CONSEQUENCES OF SUBMITTING AND PUBLISHING YOUR CONTENT ON THE SERVICE. YOU HEREBY AFFIRM, REPRESENT, AND WARRANT THAT YOU OWN OR HAVE THE NECESSARY LICENSES, RIGHTS, CONSENTS, AND PERMISSIONS TO PUBLISH CONTENT YOU SUBMIT; AND YOU LICENSE TO EMUQ ALL PATENT, TRADEMARK, TRADE SECRET, COPYRIGHT OR OTHER INTELLECTUAL PROPERTY AND PROPRIETARY RIGHTS IN AND TO SUCH CONTENT FOR PUBLICATION ON THE SERVICE PURSUANT TO THESE TERMS OF SERVICE.
                BY SUBMITTING CONTENT TO EMUQ, YOU HEREBY GRANT EMUQ A WORLDWIDE, NON-EXCLUSIVE, ROYALTY-FREE, SUBLICENSEABLE AND TRANSFERABLE LICENSE TO USE, REPRODUCE, DISTRIBUTE, PREPARE DERIVATIVE WORKS OF, DISPLAY, AND PERFORM THE CONTENT IN CONNECTION WITH THE SERVICE AND EMUQ'S (AND ITS SUCCESSORS' AND AFFILIATES') BUSINESS, INCLUDING WITHOUT LIMITATION FOR PROMOTING AND REDISTRIBUTING PART OR ALL OF THE SERVICE (AND DERIVATIVE WORKS THEREOF) IN ANY MEDIA FORMATS AND THROUGH ANY MEDIA CHANNELS IN PERPETUITY. YOU ALSO HEREBY GRANT EACH USER OF THE SERVICE A NON-EXCLUSIVE LICENSE TO ACCESS YOUR CONTENT THROUGH THE SERVICE, AND TO USE, REPRODUCE, DISTRIBUTE, DISPLAY AND PERFORM SUCH CONTENT AS PERMITTED THROUGH THE FUNCTIONALITY OF THE SERVICE AND UNDER THESE TERMS OF SERVICE. THE ABOVE LICENSES GRANTED BY YOU IN CONTENT YOU SUBMIT ARE PERPETUAL AND IRREVOCABLE.
                YOU FURTHER AGREE THAT CONTENT YOU SUBMIT TO THE SERVICE WILL NOT CONTAIN THIRD PARTY COPYRIGHTED MATERIAL, OR MATERIAL THAT IS SUBJECT TO OTHER THIRD PARTY PROPRIETARY RIGHTS, UNLESS YOU HAVE PRIOR WRITTEN PERMISSION FROM THE RIGHTFUL OWNER OF THE MATERIAL OR YOU ARE OTHERWISE LEGALLY ENTITLED TO POST THE MATERIAL AND TO GRANT EMUQ ALL OF THE LICENSE RIGHTS GRANTED HEREIN.
                YOU FURTHER AGREE THAT YOU WILL NOT SUBMIT TO THE SERVICE ANY CONTENT OR OTHER MATERIAL THAT IS CONTRARY TO THE APPLICABLE LOCAL, NATIONAL, AND INTERNATIONAL LAWS AND REGULATIONS.
                EMUQ DOES NOT ENDORSE ANY CONTENT SUBMITTED TO THE SERVICE BY ANY USER OR OTHER LICENSOR, OR ANY OPINION, RECOMMENDATION, OR ADVICE EXPRESSED THEREIN, AND EMUQ EXPRESSLY DISCLAIMS ANY AND ALL LIABILITY IN CONNECTION WITH CONTENT. EMUQ DOES NOT PERMIT COPYRIGHT INFRINGING ACTIVITIES AND INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS ON THE SERVICE, AND EMUQ WILL REMOVE ALL CONTENT IF PROPERLY NOTIFIED THAT SUCH CONTENT INFRINGES ON ANOTHER'S INTELLECTUAL PROPERTY RIGHTS. EMUQ RESERVES THE RIGHT TO REMOVE CONTENT WITHOUT PRIOR NOTICE.
                YOU UNDERSTAND THAT EMUQ WILL HAVE ACCESS TO ANY AND ALL INFORMATION YOU PROVIDE TO EMUQ AND THAT, EVEN IF YOU POST ANONYMOUSLY OR UNDER A PSEUDONYM, EMUQ WILL BE ABLE TO IDENTIFY YOU AND CONTACT YOU IN THE EVENT IT IS DEEMED NECESSARY.
                YOU ALSO ACKNOWLEDGE THAT THE INTERNET MAY BE SUBJECT TO BREACHES OF SECURITY AND THAT THE SUBMISSION OF CONTENT OR OTHER INFORMATION MAY NOT BE SECURE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>6(A). SOUND RECORDING UPLOADS</span>
                EMUQ HAS THE SOLE AND EXCLUSIVE RIGHT TO APPROVE ALL CONTENT ON THE EMUQ WEBSITE/APPLICATIONS; PROVIDED, HOWEVER, THAT IF ANY PERSON OR ENTITY IS INTERESTED IN HAVING ITS SOUND RECORDINGS ON THE EMUQ WEBSITE/APPLICATION THAT PERSON OR ENTITY SHOULD CONTACT EMUQ AT CONTACT@EMUQ.COM FOR APPROVAL. FURTHER DETAILS WILL BE PROVIDED TO YOU THEN.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>7. ACCOUNT TERMINATION POLICY</span><br/>
                EMUQ WILL TERMINATE A USER'S ACCESS TO THE SERVICE IF, UNDER APPROPRIATE CIRCUMSTANCES, THE USER IS DETERMINED TO BE A REPEAT INFRINGER.
                EMUQ RESERVES THE RIGHT TO DECIDE WHETHER CONTENT VIOLATES THESE TERMS OF SERVICE FOR REASONS OTHER THAN COPYRIGHT INFRINGEMENT, SUCH AS, BUT NOT LIMITED TO, OBSCENITY OR EXCESSIVE LENGTH, OR FOR ANY REASON IN EMUQ’S SOLE BUSINESS JUDGMENT. EMUQ MAY AT ANY TIME, WITHOUT PRIOR NOTICE AND IN ITS SOLE DISCRETION, REMOVE SUCH CONTENT AND/OR TERMINATE A USER'S ACCOUNT FOR SUBMITTING SUCH MATERIAL IN VIOLATION OF THESE TERMS OF SERVICE. CONTENT REMOVED FROM THE SERVICE MAY CONTINUE TO BE STORED BY EMUQ INCLUDING, WITHOUT LIMITATION, IN ORDER TO COMPLY WITH CERTAIN LEGAL OBLIGATIONS, BUT MAY NOT BE RETRIEVABLE WITHOUT A VALID COURT ORDER. CONSEQUENTLY, EMUQ ENCOURAGES YOU TO MAINTAIN YOUR OWN BACKUP OF YOUR CONTENT. EMUQ IS NOT A BACKUP SERVICE AND YOU AGREE THAT YOU WILL NOT RELY ON THE SERVICE FOR THE PURPOSES OF CONTENT BACKUP OR STORAGE. EMUQ WILL NOT BE LIABLE TO YOU FOR ANY MODIFICATION, SUSPENSION, OR DISCONTINUATION OF THE SERVICES, OR THE LOSS OF ANY CONTENT.
                  </div>

                 <div className="lorem-ipsum-dolor-si">
                <span>8. WARRANTY DISCLAIMER</span><br/>
                YOU AGREE THAT YOUR USE OF THE SERVICES SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW. EMUQ, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SERVICES AND YOUR USE THEREOF. EMUQ.COM MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES. EMUQ.COM DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICES OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND EMUQ.COM WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>9. LIMITATION OF LIABILITY</span><br/>
                IN NO EVENT SHALL EMUQ TECH, INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICES, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.YOU SPECIFICALLY ACKNOWLEDGE THAT EMUQ.COM SHALL NOT BE LIABLE FOR CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>10. SERVICE</span><br/>
                THE SERVICE IS CONTROLLED AND OFFERED BY EMUQ FROM ITS FACILITIES IN THE UNITED STATES OF AMERICA. EMUQ MAKES NO REPRESENTATIONS THAT THE SERVICE IS APPROPRIATE OR AVAILABLE FOR USE IN OTHER LOCATIONS. THOSE WHO ACCESS OR USE THE SERVICE FROM OTHER JURISDICTIONS DO SO AT THEIR OWN VOLITION AND ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAW.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>11. INDEMNITY</span><br/>
                YOU HEREBY AGREE TO DEFEND, INDEMNIFY AND HOLD HARMLESS EMUQ, ITS PARENT CORPORATION, OFFICERS, DIRECTORS, EMPLOYEES AND AGENTS, FROM AND AGAINST ANY AND ALL CLAIMS, DAMAGES, OBLIGATIONS, LOSSES, LIABILITIES, COSTS OR DEBT, AND EXPENSES (INCLUDING BUT NOT LIMITED TO ATTORNEY'S FEES) ARISING FROM: (I) YOUR USE OF AND ACCESS TO THE SERVICE; (II) YOUR VIOLATION OF ANY TERM OF THESE TERMS OF SERVICE; (III) YOUR VIOLATION OF ANY THIRD PARTY RIGHT, INCLUDING WITHOUT LIMITATION ANY COPYRIGHT, PROPERTY, OR PRIVACY RIGHT; OR (IV) ANY CLAIM THAT YOUR CONTENT CAUSED DAMAGE TO A THIRD PARTY. THIS DEFENSE AND INDEMNIFICATION OBLIGATION WILL SURVIVE THESE TERMS OF SERVICE AND YOUR USE OF THE SERVICE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>12. ABILITY TO ACCEPT TERMS OF SERVICE</span><br/>
                YOU AFFIRM THAT YOU ARE EITHER MORE THAN 18 YEARS OF AGE, OR AN EMANCIPATED MINOR, OR POSSESS LEGAL PARENTAL OR GUARDIAN CONSENT, AND ARE FULLY ABLE AND COMPETENT TO ENTER INTO THE TERMS, CONDITIONS, OBLIGATIONS, AFFIRMATIONS, REPRESENTATIONS, AND WARRANTIES SET FORTH IN THESE TERMS OF SERVICE, AND TO ABIDE BY AND COMPLY WITH THESE TERMS OF SERVICE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>13. ASSIGNMENT</span><br/>
                THESE TERMS OF SERVICE, AND ANY RIGHTS AND LICENSES GRANTED HEREUNDER, MAY NOT BE TRANSFERRED OR ASSIGNED BY YOU, BUT MAY BE ASSIGNED BY EMUQ WITHOUT RESTRICTION.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>14. MISCELLANEOUS (A)</span><br/> THE SITE AND SERVICES MAY BE USED AND ACCESSED SOLELY FOR LAWFUL PURPOSES. YOU AGREE TO ABIDE BY ALL APPLICABLE LOCAL, STATE, NATIONAL AND FOREIGN LAWS, TREATISES AND REGULATIONS IN CONNECTION WITH YOUR USE OF THE SITE AND SERVICES. IN ADDITION, WITHOUT LIMITATION, YOU AGREE THAT YOU WILL NOT DO ANY OF THE FOLLOWING WHILE USING OR ACCESSING THE SITE AND SERVICES:
                DISABLE, HACK, CIRCUMVENT OR OTHERWISE INTERFERE WITH SECURITY RELATED FEATURES OF THE SITE OR FEATURES THAT PREVENT OR RESTRICT USE OR COPYING OF ANY EMUQ CONTENT OR MATERIALS;
                USE ANY METADATA, META TAGS OR OTHER HIDDEN TEXT UTILIZING A EMUQ NAME, TRADEMARK, URL OR PRODUCT NAME;
                UPLOAD, SUBMIT, POST, EMAIL OR OTHERWISE TRANSMIT ANY UNSOLICITED OR UNAUTHORIZED ADVERTISING, PROMOTIONAL MATERIALS, JUNK MAIL, SPAM, CHAIN LETTERS, SO-CALLED PYRAMID SCHEMES OR ANY OTHER FORM OF SOLICITATION;
                FORGE ANY TCP/IP PACKET HEADER OR ANY PART OF THE HEADER INFORMATION IN ANY POSTING OR IN ANY WAY USE THE SITE OR SERVICES TO SEND ALTERED, DECEPTIVE OR FALSE SOURCE-IDENTIFYING INFORMATION;
                UPLOAD, SUBMIT, POST, EMAIL, OR OTHERWISE TRANSMIT, VIA THE SITE OR SERVICES, ANY RECORDINGS OR OTHER MATERIALS THAT ARE, IN THE SOLE OPINION OF EMUQ, UNLAWFUL, HARMFUL, THREATENING, OBSCENE, HARASSING, DEFAMATORY OR HATEFUL OR THAT CONTAIN OBJECTS OR SYMBOLS OF HATE, INVADE THE PRIVACY OF ANY THIRD PARTY, CONTAIN NUDITY (INCLUDING, WITHOUT LIMITATION, ANY PORNOGRAPHY, EROTICA, CHILD PORNOGRAPHY OR CHILD EROTICA), ARE DECEPTIVE, THREATENING, ABUSIVE, INCITING OF UNLAWFUL ACTION, DEFAMATORY, LIBELOUS, VULGAR OR VIOLENT OR CONSTITUTE HATE SPEECH OR ARE OTHERWISE OBJECTIONABLE;
                DESTROY, INTERFERE WITH OR DISRUPT, OR ATTEMPT TO INTERFERE WITH OR DISRUPT, ANY WEB PAGES AVAILABLE ON THE SITE, SERVERS OR NETWORKS CONNECTED TO THE SITE OR THE TECHNICAL DELIVERY SYSTEMS OF EMUQ’S PROVIDERS OR BREAK ANY REQUIREMENTS, PROCEDURES, POLICIES OR REGULATIONS OF NETWORKS CONNECTED TO THE SITE;
                ATTEMPT TO SCAN, PROBE OR TEST THE VULNERABILITY OF ANY EMUQ SYSTEM OR NETWORK OR BREACH, IMPAIR OR CIRCUMVENT ANY SECURITY OR AUTHENTICATION MEASURES PROTECTING AND PROVIDING SECURITY FOR THE SITE OR SERVICES;
                ATTEMPT TO DECOMPILE, DISASSEMBLE, DECIPHER OR REVERSE ENGINEER ANY OF THE SOFTWARE USED TO PROVIDE THE SITE OR SERVICES;
                ATTEMPT TO SEARCH, META-SEARCH OR ACCESS THE SITE WITH ANY ENGINE, SOFTWARE, TOOL, AGENT, DEVICE OR MECHANISM OTHER THAN SOFTWARE AND/OR SEARCH AGENTS PROVIDED BY EMUQ OR OTHER GENERALLY AVAILABLE THIRD PARTY WEB BROWSERS (E.G., INTERNET EXPLORER, FIREFOX, SAFARI), INCLUDING, WITHOUT LIMITATION, ANY SOFTWARE THAT SENDS QUERIES TO THE SITE TO DETERMINE HOW A WEBSITE OR WEB PAGE RANKS;
                COLLECT OR STORE PERSONAL DATA ABOUT OTHER USERS OF THE SITE OR SERVICES WITHOUT THEIR EXPRESS AND EXPLICIT PERMISSION;
                MISREPRESENT OR IMPERSONATE YOUR AFFILIATION WITH ANY PERSON OR ENTITY, THROUGH PRETEXT OR SOME OTHER FORM OF SOCIAL ENGINEERING OR OTHERWISE COMMIT FRAUD;
                USE THE SITE OR SERVICES IN ANY MANNER NOT PERMITTED BY THE TERMS OF SERVICE; OR
                INSTRUCT OR ENCOURAGE ANY OTHER INDIVIDUAL TO DO ANY OF THE FOREGOING OR TO BREACH AND/OR VIOLATE ANY OF THE TERMS OF SERVICE.
                 </div>
                 <div className="lorem-ipsum-dolor-si">
                <span>15. GENERAL</span><br/>
                YOU AGREE THAT: (I) THE SERVICE SHALL BE DEEMED SOLELY BASED IN NEW YORK, NEW YORK; AND (II) THE SERVICE SHALL BE DEEMED A PASSIVE WEBSITE THAT DOES NOT GIVE RISE TO PERSONAL JURISDICTION OVER EMUQ, EITHER SPECIFIC OR GENERAL, IN JURISDICTIONS OTHER THAN NEW YORK, NEW YORK. THESE TERMS OF SERVICE SHALL BE GOVERNED BY THE INTERNAL SUBSTANTIVE LAWS OF THE STATE OF NEW YORK, WITHOUT RESPECT TO ITS CONFLICT OF LAWS PRINCIPLES. ANY CLAIM OR DISPUTE BETWEEN YOU AND EMUQ THAT ARISES IN WHOLE OR IN PART FROM THE SERVICE SHALL BE DECIDED EXCLUSIVELY BY A COURT OF COMPETENT JURISDICTION LOCATED IN THE CITY, COUNTY AND STATE OF NEW YORK. THESE TERMS OF SERVICE, TOGETHER WITH ANY OTHER LEGAL NOTICES PUBLISHED BY EMUQ ON THE SERVICE, SHALL CONSTITUTE THE ENTIRE AGREEMENT BETWEEN YOU AND EMUQ CONCERNING THE SERVICE. IF ANY PROVISION OF THESE TERMS OF SERVICE IS DEEMED INVALID BY A COURT OF COMPETENT JURISDICTION, THE INVALIDITY OF SUCH PROVISION SHALL NOT AFFECT THE VALIDITY OF THE REMAINING PROVISIONS OF THESE TERMS OF SERVICE, WHICH SHALL REMAIN IN FULL FORCE AND EFFECT. NO WAIVER OF ANY TERM OF THIS THESE TERMS OF SERVICE SHALL BE DEEMED A FURTHER OR CONTINUING WAIVER OF SUCH TERM OR ANY OTHER TERM, AND EMUQ'S FAILURE TO ASSERT ANY RIGHT OR PROVISION UNDER THESE TERMS OF SERVICE SHALL NOT CONSTITUTE A WAIVER OF SUCH RIGHT OR PROVISION. EMUQ RESERVES THE RIGHT TO AMEND THESE TERMS OF SERVICE AT ANY TIME AND WITHOUT NOTICE, AND IT IS YOUR RESPONSIBILITY TO REVIEW THESE TERMS OF SERVICE FOR ANY CHANGES. YOUR USE OF THE SERVICE FOLLOWING ANY AMENDMENT OF THESE TERMS OF SERVICE WILL SIGNIFY YOUR ASSENT TO AND ACCEPTANCE OF ITS REVISED TERMS.
                YOU AND EMUQ AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
                  </div>
          </div>
          </div>
        </div>
        <div className="container-center-horizontal">
          <Header/>
        </div>
        <div className="container-center-horizontal">
          <Footer/>
        </div>
      </div>
    );
  }
}


class Fypsoundslogo extends React.Component {
  render() {
    const { fypsoundsLogo } = this.props;

    return <div className="fypsoundslogo-NOXmfT" style={{ backgroundImage: `url(${fypsoundsLogo})` }}></div>;
  }
}


class About extends React.Component {
  render() {
    const { about } = this.props;

    return (
      <div className="container-center-horizontal footer-items">
          <a href="/about">
            <div className="montserrat-semi-bold-white-14px">{about}</div>
          </a>
      </div>
    );
  }
}


class Fypsoundslogo2 extends React.Component {
  render() {
    const { fypsoundsLogo } = this.props;

    return (
      <div className="container-center-horizontal">
        <div className="fypsoundslogo-iPe1yZ" style={{ backgroundImage: `url(${fypsoundsLogo})` }}></div>
      </div>
    );
  }
}
